//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcosService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexCase", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexCase : object
    {
        
        private System.Guid CaseIdField;
        
        private string CaseTitleField;
        
        private string DnrField;
        
        private string[] RelatedObjectsField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CaseId
        {
            get
            {
                return this.CaseIdField;
            }
            set
            {
                this.CaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseTitle
        {
            get
            {
                return this.CaseTitleField;
            }
            set
            {
                this.CaseTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dnr
        {
            get
            {
                return this.DnrField;
            }
            set
            {
                this.DnrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RelatedObjects
        {
            get
            {
                return this.RelatedObjectsField;
            }
            set
            {
                this.RelatedObjectsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexOccurrence", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexOccurrence : object
    {
        
        private EcosService.ReflexDocumentMetadata[] DocumentsField;
        
        private bool HasSensitiveDocumentsField;
        
        private System.DateTime OccurenceDateField;
        
        private string OccurenceTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.ReflexDocumentMetadata[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSensitiveDocuments
        {
            get
            {
                return this.HasSensitiveDocumentsField;
            }
            set
            {
                this.HasSensitiveDocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurenceDate
        {
            get
            {
                return this.OccurenceDateField;
            }
            set
            {
                this.OccurenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccurenceTitle
        {
            get
            {
                return this.OccurenceTitleField;
            }
            set
            {
                this.OccurenceTitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexDocumentMetadata", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexDocumentMetadata : object
    {
        
        private System.Guid DocumentIdField;
        
        private string DocumentTitleField;
        
        private bool HasFileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTitle
        {
            get
            {
                return this.DocumentTitleField;
            }
            set
            {
                this.DocumentTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasFile
        {
            get
            {
                return this.HasFileField;
            }
            set
            {
                this.HasFileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexFile", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexFile : object
    {
        
        private byte[] DataField;
        
        private string FilenameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexFullCase", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexFullCase : object
    {
        
        private System.Guid CaseIdField;
        
        private string CaseNumberField;
        
        private string CaseSubtitleField;
        
        private string CaseSubtitleFreeField;
        
        private EcosService.ReflexDocumentListItem[] DocumentsField;
        
        private string EstateAddressField;
        
        private string EstateDesignationField;
        
        private bool IsConfidentialField;
        
        private EcosService.ReflexOccurrenceListItem[] OccurrencesField;
        
        private string ProcessTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CaseId
        {
            get
            {
                return this.CaseIdField;
            }
            set
            {
                this.CaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber
        {
            get
            {
                return this.CaseNumberField;
            }
            set
            {
                this.CaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseSubtitle
        {
            get
            {
                return this.CaseSubtitleField;
            }
            set
            {
                this.CaseSubtitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseSubtitleFree
        {
            get
            {
                return this.CaseSubtitleFreeField;
            }
            set
            {
                this.CaseSubtitleFreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.ReflexDocumentListItem[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstateAddress
        {
            get
            {
                return this.EstateAddressField;
            }
            set
            {
                this.EstateAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstateDesignation
        {
            get
            {
                return this.EstateDesignationField;
            }
            set
            {
                this.EstateDesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfidential
        {
            get
            {
                return this.IsConfidentialField;
            }
            set
            {
                this.IsConfidentialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.ReflexOccurrenceListItem[] Occurrences
        {
            get
            {
                return this.OccurrencesField;
            }
            set
            {
                this.OccurrencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessTypeName
        {
            get
            {
                return this.ProcessTypeNameField;
            }
            set
            {
                this.ProcessTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexDocumentListItem", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexDocumentListItem : object
    {
        
        private EcosService.ReflexDecisionBasis[] DecisionBasesField;
        
        private string DocumentClassificationTypeDescriptionField;
        
        private System.Guid DocumentIdField;
        
        private System.Guid DocumentKindIdField;
        
        private string DocumentStatusField;
        
        private System.Guid DocumentTypeIdField;
        
        private string FilenameField;
        
        private bool IsConfidentialField;
        
        private bool IsMainDecisionField;
        
        private string NoteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.ReflexDecisionBasis[] DecisionBases
        {
            get
            {
                return this.DecisionBasesField;
            }
            set
            {
                this.DecisionBasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentClassificationTypeDescription
        {
            get
            {
                return this.DocumentClassificationTypeDescriptionField;
            }
            set
            {
                this.DocumentClassificationTypeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentKindId
        {
            get
            {
                return this.DocumentKindIdField;
            }
            set
            {
                this.DocumentKindIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentStatus
        {
            get
            {
                return this.DocumentStatusField;
            }
            set
            {
                this.DocumentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentTypeId
        {
            get
            {
                return this.DocumentTypeIdField;
            }
            set
            {
                this.DocumentTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfidential
        {
            get
            {
                return this.IsConfidentialField;
            }
            set
            {
                this.IsConfidentialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMainDecision
        {
            get
            {
                return this.IsMainDecisionField;
            }
            set
            {
                this.IsMainDecisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexOccurrenceListItem", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexOccurrenceListItem : object
    {
        
        private EcosService.ReflexDocumentListItem[] DocumentsField;
        
        private bool IsConfidentialField;
        
        private System.DateTime OccurrenceDateField;
        
        private string OccurrenceDescriptionField;
        
        private System.Guid OccurrenceIdField;
        
        private System.Guid OccurrenceKindIdField;
        
        private System.Guid OccurrenceTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.ReflexDocumentListItem[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfidential
        {
            get
            {
                return this.IsConfidentialField;
            }
            set
            {
                this.IsConfidentialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurrenceDate
        {
            get
            {
                return this.OccurrenceDateField;
            }
            set
            {
                this.OccurrenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccurrenceDescription
        {
            get
            {
                return this.OccurrenceDescriptionField;
            }
            set
            {
                this.OccurrenceDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OccurrenceId
        {
            get
            {
                return this.OccurrenceIdField;
            }
            set
            {
                this.OccurrenceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OccurrenceKindId
        {
            get
            {
                return this.OccurrenceKindIdField;
            }
            set
            {
                this.OccurrenceKindIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OccurrenceTypeId
        {
            get
            {
                return this.OccurrenceTypeIdField;
            }
            set
            {
                this.OccurrenceTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexDecisionBasis", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexDecisionBasis : object
    {
        
        private string DescriptionField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexGuidNamePair", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexGuidNamePair : object
    {
        
        private System.Guid IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexSearchCase", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class ReflexSearchCase : object
    {
        
        private EcosService.Filter[] FiltersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.Filter[] Filters
        {
            get
            {
                return this.FiltersField;
            }
            set
            {
                this.FiltersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.OrFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.AndFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.NotFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.SinglePartyRoleFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.MultiPartyRoleFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.WatchDateFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.CaseStartDateFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.DocumentKindFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.DocumentTypeFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.DocumentStatusFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.CaseNumberFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.FnrFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.OccurrenceFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.MainDecisionFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EcosService.CaseStatusIdFilter))]
    public partial class Filter : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class OrFilter : EcosService.Filter
    {
        
        private EcosService.Filter[] FiltersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.Filter[] Filters
        {
            get
            {
                return this.FiltersField;
            }
            set
            {
                this.FiltersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AndFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class AndFilter : EcosService.Filter
    {
        
        private EcosService.Filter[] FiltersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.Filter[] Filters
        {
            get
            {
                return this.FiltersField;
            }
            set
            {
                this.FiltersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class NotFilter : EcosService.Filter
    {
        
        private EcosService.Filter FilterField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.Filter Filter
        {
            get
            {
                return this.FilterField;
            }
            set
            {
                this.FilterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinglePartyRoleFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class SinglePartyRoleFilter : EcosService.Filter
    {
        
        private System.Guid PartyIdField;
        
        private System.Guid RoleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PartyId
        {
            get
            {
                return this.PartyIdField;
            }
            set
            {
                this.PartyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiPartyRoleFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class MultiPartyRoleFilter : EcosService.Filter
    {
        
        private EcosService.PartyRoleTuple[] PartyRolesField;
        
        private bool RequireAllField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.PartyRoleTuple[] PartyRoles
        {
            get
            {
                return this.PartyRolesField;
            }
            set
            {
                this.PartyRolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequireAll
        {
            get
            {
                return this.RequireAllField;
            }
            set
            {
                this.RequireAllField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WatchDateFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class WatchDateFilter : EcosService.Filter
    {
        
        private System.DateTime DateTimeField;
        
        private EcosService.DateTimeComparison DateTimeComparisonField;
        
        private System.Guid WatchDateTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EcosService.DateTimeComparison DateTimeComparison
        {
            get
            {
                return this.DateTimeComparisonField;
            }
            set
            {
                this.DateTimeComparisonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WatchDateTypeId
        {
            get
            {
                return this.WatchDateTypeIdField;
            }
            set
            {
                this.WatchDateTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseStartDateFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class CaseStartDateFilter : EcosService.Filter
    {
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentKindFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class DocumentKindFilter : EcosService.Filter
    {
        
        private System.Guid DocumentKindIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentKindId
        {
            get
            {
                return this.DocumentKindIdField;
            }
            set
            {
                this.DocumentKindIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentTypeFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class DocumentTypeFilter : EcosService.Filter
    {
        
        private System.Guid DocumentTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentTypeId
        {
            get
            {
                return this.DocumentTypeIdField;
            }
            set
            {
                this.DocumentTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentStatusFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class DocumentStatusFilter : EcosService.Filter
    {
        
        private System.Guid DocumentStatusIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentStatusId
        {
            get
            {
                return this.DocumentStatusIdField;
            }
            set
            {
                this.DocumentStatusIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseNumberFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class CaseNumberFilter : EcosService.Filter
    {
        
        private string CaseNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber
        {
            get
            {
                return this.CaseNumberField;
            }
            set
            {
                this.CaseNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FnrFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class FnrFilter : EcosService.Filter
    {
        
        private int FnrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fnr
        {
            get
            {
                return this.FnrField;
            }
            set
            {
                this.FnrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OccurrenceFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class OccurrenceFilter : EcosService.Filter
    {
        
        private System.Nullable<System.DateTime> OccurrenceDateField;
        
        private System.Guid OccurrenceTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OccurrenceDate
        {
            get
            {
                return this.OccurrenceDateField;
            }
            set
            {
                this.OccurrenceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OccurrenceTypeId
        {
            get
            {
                return this.OccurrenceTypeIdField;
            }
            set
            {
                this.OccurrenceTypeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainDecisionFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class MainDecisionFilter : EcosService.Filter
    {
        
        private bool HasMainDecisionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMainDecision
        {
            get
            {
                return this.HasMainDecisionField;
            }
            set
            {
                this.HasMainDecisionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaseStatusIdFilter", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class CaseStatusIdFilter : EcosService.Filter
    {
        
        private System.Guid CaseStatusIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CaseStatusId
        {
            get
            {
                return this.CaseStatusIdField;
            }
            set
            {
                this.CaseStatusIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartyRoleTuple", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public partial class PartyRoleTuple : object
    {
        
        private System.Guid PartyIdField;
        
        private System.Guid RoleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PartyId
        {
            get
            {
                return this.PartyIdField;
            }
            set
            {
                this.PartyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeComparison", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract.Reflex")]
    public enum DateTimeComparison : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Passed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPassed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReflexSearchCaseResult", Namespace="http://schemas.datacontract.org/2004/07/Ecos2PublicServices.DataContract")]
    public partial class ReflexSearchCaseResult : object
    {
        
        private System.Nullable<System.Guid> CaseIdField;
        
        private string CaseNumberField;
        
        private string CaseSubtitleField;
        
        private string CaseSubtitleFreeField;
        
        private string EstateDesignationField;
        
        private string ProcessTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CaseId
        {
            get
            {
                return this.CaseIdField;
            }
            set
            {
                this.CaseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseNumber
        {
            get
            {
                return this.CaseNumberField;
            }
            set
            {
                this.CaseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseSubtitle
        {
            get
            {
                return this.CaseSubtitleField;
            }
            set
            {
                this.CaseSubtitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseSubtitleFree
        {
            get
            {
                return this.CaseSubtitleFreeField;
            }
            set
            {
                this.CaseSubtitleFreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstateDesignation
        {
            get
            {
                return this.EstateDesignationField;
            }
            set
            {
                this.EstateDesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessTypeName
        {
            get
            {
                return this.ProcessTypeNameField;
            }
            set
            {
                this.ProcessTypeNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EcosService.IReflexService")]
    public interface IReflexService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflexService/GetEstateCases", ReplyAction="http://tempuri.org/IReflexService/GetEstateCasesResponse")]
        System.Threading.Tasks.Task<EcosService.ReflexCase[]> GetEstateCasesAsync(int fnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflexService/GetCaseOccurences", ReplyAction="http://tempuri.org/IReflexService/GetCaseOccurencesResponse")]
        System.Threading.Tasks.Task<EcosService.ReflexOccurrence[]> GetCaseOccurencesAsync(System.Guid caseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflexService/GetDocumentFile", ReplyAction="http://tempuri.org/IReflexService/GetDocumentFileResponse")]
        System.Threading.Tasks.Task<EcosService.ReflexFile> GetDocumentFileAsync(System.Guid documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflexService/GetCase", ReplyAction="http://tempuri.org/IReflexService/GetCaseResponse")]
        System.Threading.Tasks.Task<EcosService.ReflexFullCase> GetCaseAsync(System.Guid caseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflexService/GetDocumentStatuses", ReplyAction="http://tempuri.org/IReflexService/GetDocumentStatusesResponse")]
        System.Threading.Tasks.Task<EcosService.ReflexGuidNamePair[]> GetDocumentStatusesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflexService/SearchCase", ReplyAction="http://tempuri.org/IReflexService/SearchCaseResponse")]
        System.Threading.Tasks.Task<EcosService.ReflexSearchCaseResult[]> SearchCaseAsync(EcosService.ReflexSearchCase model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IReflexServiceChannel : EcosService.IReflexService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ReflexServiceClient : System.ServiceModel.ClientBase<EcosService.IReflexService>, EcosService.IReflexService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReflexServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReflexServiceClient.GetBindingForEndpoint(endpointConfiguration), ReflexServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReflexServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReflexServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReflexServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReflexServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReflexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EcosService.ReflexCase[]> GetEstateCasesAsync(int fnr)
        {
            return base.Channel.GetEstateCasesAsync(fnr);
        }
        
        public System.Threading.Tasks.Task<EcosService.ReflexOccurrence[]> GetCaseOccurencesAsync(System.Guid caseId)
        {
            return base.Channel.GetCaseOccurencesAsync(caseId);
        }
        
        public System.Threading.Tasks.Task<EcosService.ReflexFile> GetDocumentFileAsync(System.Guid documentId)
        {
            return base.Channel.GetDocumentFileAsync(documentId);
        }
        
        public System.Threading.Tasks.Task<EcosService.ReflexFullCase> GetCaseAsync(System.Guid caseId)
        {
            return base.Channel.GetCaseAsync(caseId);
        }
        
        public System.Threading.Tasks.Task<EcosService.ReflexGuidNamePair[]> GetDocumentStatusesAsync()
        {
            return base.Channel.GetDocumentStatusesAsync();
        }
        
        public System.Threading.Tasks.Task<EcosService.ReflexSearchCaseResult[]> SearchCaseAsync(EcosService.ReflexSearchCase model)
        {
            return base.Channel.SearchCaseAsync(model);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReflexService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReflexService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReflexService))
            {
                return new System.ServiceModel.EndpointAddress("http://pub-env-t02.utv.sokigo.com/Ecos2DSKundPublicServices/ReflexService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReflexService1))
            {
                return new System.ServiceModel.EndpointAddress("https://ecos2test.sokigo.com/Ecos2DSKundPublicServices/ReflexService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReflexService,
            
            BasicHttpBinding_IReflexService1,
        }
    }
}
