// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var befolkningSenasteadressPid = BefolkningSenasteadressPid.FromJson(jsonString);

using Newtonsoft.Json;

namespace FbService.QuickType.BefolkningSenasteadressPid
{
    public class BefolkningSenasteadressPid
    {
        [JsonProperty("statusKod", NullValueHandling = NullValueHandling.Ignore)]
        public long? StatusKod { get; set; }

        [JsonProperty("statusMeddelande", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusMeddelande { get; set; }

        [JsonProperty("fel", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Fel { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("pid", NullValueHandling = NullValueHandling.Ignore)]
        public int Pid { get; set; }

        [JsonProperty("grupp", NullValueHandling = NullValueHandling.Ignore)]
        public Grupp[] Grupp { get; set; }
    }

    public class Grupp
    {
        [JsonProperty("pid", NullValueHandling = NullValueHandling.Ignore)]
        public long? Pid { get; set; }

        [JsonProperty("adresstyp", NullValueHandling = NullValueHandling.Ignore)]
        public string Adresstyp { get; set; }

        [JsonProperty("lopnummer", NullValueHandling = NullValueHandling.Ignore)]
        public long? Lopnummer { get; set; }

        [JsonProperty("franDatum", NullValueHandling = NullValueHandling.Ignore)]
        public string FranDatum { get; set; }

        [JsonProperty("gallerTillDatum", NullValueHandling = NullValueHandling.Ignore)]
        public string GallerTillDatum { get; set; }

        [JsonProperty("coAdress", NullValueHandling = NullValueHandling.Ignore)]
        public string CoAdress { get; set; }

        [JsonProperty("utdelningsadress1", NullValueHandling = NullValueHandling.Ignore)]
        public string Utdelningsadress1 { get; set; }

        [JsonProperty("utdelningsadress2", NullValueHandling = NullValueHandling.Ignore)]
        public string Utdelningsadress2 { get; set; }

        [JsonProperty("utdelningsadress3", NullValueHandling = NullValueHandling.Ignore)]
        public string Utdelningsadress3 { get; set; }

        [JsonProperty("postnummer", NullValueHandling = NullValueHandling.Ignore)]
        public string Postnummer { get; set; }

        [JsonProperty("postort", NullValueHandling = NullValueHandling.Ignore)]
        public string Postort { get; set; }

        [JsonProperty("land", NullValueHandling = NullValueHandling.Ignore)]
        public string Land { get; set; }

        [JsonProperty("adressplatsId", NullValueHandling = NullValueHandling.Ignore)]
        public long? AdressplatsId { get; set; }

        [JsonProperty("lagenhetId", NullValueHandling = NullValueHandling.Ignore)]
        public long? LagenhetId { get; set; }

        [JsonProperty("distriktskod", NullValueHandling = NullValueHandling.Ignore)]
        public string Distriktskod { get; set; }
    }
}
