// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var befolkningSenasteadressPid = BefolkningSenasteadressPid.FromJson(jsonString);

using System.Text.Json.Serialization;

namespace FbService.QuickType.BefolkningSenasteadressPid
{
    public class BefolkningSenasteadressPid
    {
        [JsonPropertyName("statusKod")]
        public long? StatusKod { get; set; }

        [JsonPropertyName("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonPropertyName("fel")]
        public string[] Fel { get; set; }

        [JsonPropertyName("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonPropertyName("pid")]
        public int Pid { get; set; }

        [JsonPropertyName("grupp")]
        public Grupp[] Grupp { get; set; }
    }

    public class Grupp
    {
        [JsonPropertyName("pid")]
        public long? Pid { get; set; }

        [JsonPropertyName("adresstyp")]
        public string Adresstyp { get; set; }

        [JsonPropertyName("lopnummer")]
        public long? Lopnummer { get; set; }

        [JsonPropertyName("franDatum")]
        public string FranDatum { get; set; }

        [JsonPropertyName("gallerTillDatum")]
        public string GallerTillDatum { get; set; }

        [JsonPropertyName("coAdress")]
        public string CoAdress { get; set; }

        [JsonPropertyName("utdelningsadress1")]
        public string Utdelningsadress1 { get; set; }

        [JsonPropertyName("utdelningsadress2")]
        public string Utdelningsadress2 { get; set; }

        [JsonPropertyName("utdelningsadress3")]
        public string Utdelningsadress3 { get; set; }

        [JsonPropertyName("postnummer")]
        public string Postnummer { get; set; }

        [JsonPropertyName("postort")]
        public string Postort { get; set; }

        [JsonPropertyName("land")]
        public string Land { get; set; }

        [JsonPropertyName("adressplatsId")]
        public long? AdressplatsId { get; set; }

        [JsonPropertyName("lagenhetId")]
        public long? LagenhetId { get; set; }

        [JsonPropertyName("distriktskod")]
        public string Distriktskod { get; set; }
    }
}
