// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var fastighetKoordinatFnr = FastighetKoordinatFnr.FromJson(jsonString);

using System.Text.Json.Serialization;

namespace FbService.QuickType.FastighetKoordinatFnr
{
    public class FastighetKoordinatFnr
    {
        [JsonPropertyName("statusKod")]
        public double? StatusKod { get; set; }

        [JsonPropertyName("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonPropertyName("fel")]
        public string[] Fel { get; set; }

        [JsonPropertyName("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonPropertyName("fnr")]
        public int Fnr { get; set; }

        [JsonPropertyName("grupp")]
        public Grupp[] Grupp { get; set; }
    }

    public class Grupp
    {
        [JsonPropertyName("koordinatUuid")]
        public string KoordinatUuid { get; set; }

        [JsonPropertyName("omrade")]
        public double? Omrade { get; set; }

        [JsonPropertyName("sweref99TMNorthingKoordinat")]
        public double? Sweref99TmNorthingKoordinat { get; set; }

        [JsonPropertyName("sweref99TMEastingKoordinat")]
        public double? Sweref99TmEastingKoordinat { get; set; }

        [JsonPropertyName("lokalNorthingKoordinat")]
        public double? LokalNorthingKoordinat { get; set; }

        [JsonPropertyName("lokalEastingKoordinat")]
        public double? LokalEastingKoordinat { get; set; }

        [JsonPropertyName("lokaltKoordinatsystemKod")]
        public string LokaltKoordinatsystemKod { get; set; }

        [JsonPropertyName("lokaltKoordinatsystem")]
        public string LokaltKoordinatsystem { get; set; }

        [JsonPropertyName("rt90NorthingKoordinat")]
        public double? Rt90NorthingKoordinat { get; set; }

        [JsonPropertyName("rt90EastingKoordinat")]
        public double? Rt90EastingKoordinat { get; set; }
    }
}
