// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var fastighetKoordinatFnr = FastighetKoordinatFnr.FromJson(jsonString);

using Newtonsoft.Json;

namespace FbService.QuickType.FastighetKoordinatFnr
{
    public class FastighetKoordinatFnr
    {
        [JsonProperty("statusKod", NullValueHandling = NullValueHandling.Ignore)]
        public long? StatusKod { get; set; }

        [JsonProperty("statusMeddelande", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusMeddelande { get; set; }

        [JsonProperty("fel", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Fel { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("fnr", NullValueHandling = NullValueHandling.Ignore)]
        public int Fnr { get; set; }

        [JsonProperty("grupp", NullValueHandling = NullValueHandling.Ignore)]
        public Grupp[] Grupp { get; set; }
    }

    public class Grupp
    {
        [JsonProperty("koordinatUuid", NullValueHandling = NullValueHandling.Ignore)]
        public string KoordinatUuid { get; set; }

        [JsonProperty("omrade", NullValueHandling = NullValueHandling.Ignore)]
        public long? Omrade { get; set; }

        [JsonProperty("sweref99TMNorthingKoordinat", NullValueHandling = NullValueHandling.Ignore)]
        public long? Sweref99TmNorthingKoordinat { get; set; }

        [JsonProperty("sweref99TMEastingKoordinat", NullValueHandling = NullValueHandling.Ignore)]
        public long? Sweref99TmEastingKoordinat { get; set; }

        [JsonProperty("lokalNorthingKoordinat", NullValueHandling = NullValueHandling.Ignore)]
        public long? LokalNorthingKoordinat { get; set; }

        [JsonProperty("lokalEastingKoordinat", NullValueHandling = NullValueHandling.Ignore)]
        public long? LokalEastingKoordinat { get; set; }

        [JsonProperty("lokaltKoordinatsystemKod", NullValueHandling = NullValueHandling.Ignore)]
        public string LokaltKoordinatsystemKod { get; set; }

        [JsonProperty("lokaltKoordinatsystem", NullValueHandling = NullValueHandling.Ignore)]
        public string LokaltKoordinatsystem { get; set; }

        [JsonProperty("rt90NorthingKoordinat", NullValueHandling = NullValueHandling.Ignore)]
        public long? Rt90NorthingKoordinat { get; set; }

        [JsonProperty("rt90EastingKoordinat", NullValueHandling = NullValueHandling.Ignore)]
        public long? Rt90EastingKoordinat { get; set; }
    }
}
