// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var befolkningSearch = BefolkningSearch.FromJson(jsonString);

using System.Text.Json.Serialization;

namespace FbService.QuickType.BefolkningSearchFolkbokfordFastighetFnr
{
    public class BefolkningSearchFolkbokfordFastighetFnr
    {
        [JsonPropertyName("statusKod")]
        public long? StatusKod { get; set; }

        [JsonPropertyName("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonPropertyName("fel")]
        public string[] Fel { get; set; }

        [JsonPropertyName("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonPropertyName("pid")]
        public int Pid { get; set; }

        [JsonPropertyName("personnummer")]
        public string Personnummer { get; set; }
    }
}
