// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var befolkningSearch = BefolkningSearch.FromJson(jsonString);

using Newtonsoft.Json;

namespace FbService.QuickType.BefolkningSearchFolkbokfordFastighetFnr
{
    public class BefolkningSearchFolkbokfordFastighetFnr
    {
        [JsonProperty("statusKod", NullValueHandling = NullValueHandling.Ignore)]
        public long? StatusKod { get; set; }

        [JsonProperty("statusMeddelande", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusMeddelande { get; set; }

        [JsonProperty("fel", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Fel { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("pid")]
        public int Pid { get; set; }

        [JsonProperty("personnummer", NullValueHandling = NullValueHandling.Ignore)]
        public string Personnummer { get; set; }
    }
}
