// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reflex.Data;

#nullable disable

namespace Reflex.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AgsConfigConfig", b =>
                {
                    b.Property<Guid>("AgsConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AgsConfigsId", "ConfigsId");

                    b.HasIndex("ConfigsId");

                    b.ToTable("AgsConfigConfig");
                });

            modelBuilder.Entity("ByggrConfigConfig", b =>
                {
                    b.Property<Guid>("ByggrConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ByggrConfigsId", "ConfigsId");

                    b.HasIndex("ConfigsId");

                    b.ToTable("ByggrConfigConfig");
                });

            modelBuilder.Entity("ConfigEcosConfig", b =>
                {
                    b.Property<Guid>("ConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EcosConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConfigsId", "EcosConfigsId");

                    b.HasIndex("EcosConfigsId");

                    b.ToTable("ConfigEcosConfig");
                });

            modelBuilder.Entity("ConfigIipaxConfig", b =>
                {
                    b.Property<Guid>("ConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IipaxConfigsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConfigsId", "IipaxConfigsId");

                    b.HasIndex("IipaxConfigsId");

                    b.ToTable("ConfigIipaxConfig");
                });

            modelBuilder.Entity("Reflex.Data.Models.AgsConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CasePattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstateNameSearch")
                        .HasColumnType("bit");

                    b.Property<string>("Instance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchWay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgsConfigs");
                });

            modelBuilder.Entity("Reflex.Data.Models.AgsSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgsSettings");
                });

            modelBuilder.Entity("Reflex.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("DefaultConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultTab")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("\"Cases\"");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultConfigId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Reflex.Data.Models.ByggrConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Diarieprefixes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HideCasesWithTextMatching")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HideConfidentialOccurences")
                        .HasColumnType("int");

                    b.Property<string>("HideDocumentsWithNoteTextMatching")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HideNotesInPreview")
                        .HasColumnType("bit");

                    b.Property<string>("HideOccurencesWithTextMatching")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MinCaseStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccurenceTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnlyActiveCases")
                        .HasColumnType("bit");

                    b.Property<bool>("OnlyCasesWithoutMainDecision")
                        .HasColumnType("bit");

                    b.Property<string>("PersonRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statuses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WorkingMaterial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ByggrConfigs");
                });

            modelBuilder.Entity("Reflex.Data.Models.ByggrSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ByggrSettings");
                });

            modelBuilder.Entity("Reflex.Data.Models.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Map")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Reflex.Data.Models.EcosConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HideConfidentialCases")
                        .HasColumnType("int");

                    b.Property<int>("HideConfidentialDocuments")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccurrenceTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessTypes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EcosConfigs");
                });

            modelBuilder.Entity("Reflex.Data.Models.EcosSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EcosSettings");
                });

            modelBuilder.Entity("Reflex.Data.Models.FbSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FbServiceDatabase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbServicePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbServiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbServiceUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbWebbBoendeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbWebbByggnadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbWebbByggnadUsrUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbWebbFastighetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbWebbFastighetUsrUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbWebbLagenhetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FbSettings");
                });

            modelBuilder.Entity("Reflex.Data.Models.IipaxConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherSecrecyVisibility")
                        .HasColumnType("int");

                    b.Property<int>("PulPersonalSecrecyVisibility")
                        .HasColumnType("int");

                    b.Property<int>("SecrecyVisibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IipaxConfigs");
                });

            modelBuilder.Entity("Reflex.Data.Models.IipaxSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IipaxSettings");
                });

            modelBuilder.Entity("Reflex.Data.Models.RolesClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RolesClaims");
                });

            modelBuilder.Entity("AgsConfigConfig", b =>
                {
                    b.HasOne("Reflex.Data.Models.AgsConfig", null)
                        .WithMany()
                        .HasForeignKey("AgsConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reflex.Data.Models.Config", null)
                        .WithMany()
                        .HasForeignKey("ConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ByggrConfigConfig", b =>
                {
                    b.HasOne("Reflex.Data.Models.ByggrConfig", null)
                        .WithMany()
                        .HasForeignKey("ByggrConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reflex.Data.Models.Config", null)
                        .WithMany()
                        .HasForeignKey("ConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigEcosConfig", b =>
                {
                    b.HasOne("Reflex.Data.Models.Config", null)
                        .WithMany()
                        .HasForeignKey("ConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reflex.Data.Models.EcosConfig", null)
                        .WithMany()
                        .HasForeignKey("EcosConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigIipaxConfig", b =>
                {
                    b.HasOne("Reflex.Data.Models.Config", null)
                        .WithMany()
                        .HasForeignKey("ConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reflex.Data.Models.IipaxConfig", null)
                        .WithMany()
                        .HasForeignKey("IipaxConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reflex.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("Reflex.Data.Models.Config", "DefaultConfig")
                        .WithMany("ApplicationUserDefaultConfig")
                        .HasForeignKey("DefaultConfigId");

                    b.Navigation("DefaultConfig");
                });

            modelBuilder.Entity("Reflex.Data.Models.Config", b =>
                {
                    b.Navigation("ApplicationUserDefaultConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
