// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var fastighetInfo = FastighetInfo.FromJson(jsonString);

using Newtonsoft.Json;

namespace FbService.QuickType.FastighetInfo
{
    public class FastighetInfoFnr
    {
        [JsonProperty("statusKod", NullValueHandling = NullValueHandling.Ignore)]
        public long? StatusKod { get; set; }

        [JsonProperty("statusMeddelande", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusMeddelande { get; set; }

        [JsonProperty("fel", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Fel { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        [JsonProperty("kommunKod", NullValueHandling = NullValueHandling.Ignore)]
        public string KommunKod { get; set; }

        [JsonProperty("kommun", NullValueHandling = NullValueHandling.Ignore)]
        public string Kommun { get; set; }

        [JsonProperty("beteckning", NullValueHandling = NullValueHandling.Ignore)]
        public string Beteckning { get; set; }

        [JsonProperty("trakt", NullValueHandling = NullValueHandling.Ignore)]
        public string Trakt { get; set; }

        [JsonProperty("beteckningsnummer", NullValueHandling = NullValueHandling.Ignore)]
        public string Beteckningsnummer { get; set; }

        [JsonProperty("block", NullValueHandling = NullValueHandling.Ignore)]
        public string Block { get; set; }

        [JsonProperty("tecken", NullValueHandling = NullValueHandling.Ignore)]
        public string Tecken { get; set; }

        [JsonProperty("enhet", NullValueHandling = NullValueHandling.Ignore)]
        public long? Enhet { get; set; }

        [JsonProperty("ofullstandigRattighetsredovisning", NullValueHandling = NullValueHandling.Ignore)]
        public bool? OfullstandigRattighetsredovisning { get; set; }

        [JsonProperty("outreddaAndelarISamfalligheter", NullValueHandling = NullValueHandling.Ignore)]
        public bool? OutreddaAndelarISamfalligheter { get; set; }

        [JsonProperty("forvarvstillstandOmarrendering", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ForvarvstillstandOmarrendering { get; set; }

        [JsonProperty("kronohemman", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Kronohemman { get; set; }

        [JsonProperty("delagareOfullstandigtRedovisade", NullValueHandling = NullValueHandling.Ignore)]
        public bool? DelagareOfullstandigtRedovisade { get; set; }

        [JsonProperty("felIFR", NullValueHandling = NullValueHandling.Ignore)]
        public bool? FelIfr { get; set; }

        [JsonProperty("underAjourforingIFR", NullValueHandling = NullValueHandling.Ignore)]
        public bool? UnderAjourforingIfr { get; set; }

        [JsonProperty("senasteAjourforingIFR", NullValueHandling = NullValueHandling.Ignore)]
        public string SenasteAjourforingIfr { get; set; }

        [JsonProperty("utanforBevakningskrets", NullValueHandling = NullValueHandling.Ignore)]
        public bool? UtanforBevakningskrets { get; set; }

        [JsonProperty("preliminarTypkod", NullValueHandling = NullValueHandling.Ignore)]
        public string PreliminarTypkod { get; set; }

        [JsonProperty("har3DOmrade", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Har3DOmrade { get; set; }

        [JsonProperty("ar3DUrholkad", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Ar3DUrholkad { get; set; }

        [JsonProperty("andelAvserUtforandeOchDrift", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AndelAvserUtforandeOchDrift { get; set; }

        [JsonProperty("samfallighetFarAndraAndel", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SamfallighetFarAndraAndel { get; set; }

        [JsonProperty("andelAvserEndastDrift", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AndelAvserEndastDrift { get; set; }

        [JsonProperty("summaAndelstal", NullValueHandling = NullValueHandling.Ignore)]
        public string SummaAndelstal { get; set; }

        [JsonProperty("arAgarlagenhet", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ArAgarlagenhet { get; set; }

        [JsonProperty("arUrholkadAvAgarlagenhet", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ArUrholkadAvAgarlagenhet { get; set; }

        [JsonProperty("forvarvstillstandGlesbygd", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ForvarvstillstandGlesbygd { get; set; }

        [JsonProperty("fnr", NullValueHandling = NullValueHandling.Ignore)]
        public long? Fnr { get; set; }

        [JsonProperty("cfdFnr", NullValueHandling = NullValueHandling.Ignore)]
        public string CfdFnr { get; set; }

        [JsonProperty("uuid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uuid { get; set; }
    }
}
