// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var fastighetInfo = FastighetInfo.FromJson(jsonString);

using System.Text.Json.Serialization;

namespace FbService.QuickType.FastighetInfoFnr
{
    public class FastighetInfoFnr
    {
        [JsonPropertyName("statusKod")]
        public long? StatusKod { get; set; }

        [JsonPropertyName("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonPropertyName("fel")]
        public string[] Fel { get; set; }

        [JsonPropertyName("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("kommunKod")]
        public string KommunKod { get; set; }

        [JsonPropertyName("kommun")]
        public string Kommun { get; set; }

        [JsonPropertyName("beteckning")]
        public string Beteckning { get; set; }

        [JsonPropertyName("trakt")]
        public string Trakt { get; set; }

        [JsonPropertyName("beteckningsnummer")]
        public string Beteckningsnummer { get; set; }

        [JsonPropertyName("block")]
        public string Block { get; set; }

        [JsonPropertyName("tecken")]
        public string Tecken { get; set; }

        [JsonPropertyName("enhet")]
        public long? Enhet { get; set; }

        [JsonPropertyName("ofullstandigRattighetsredovisning")]
        public bool? OfullstandigRattighetsredovisning { get; set; }

        [JsonPropertyName("outreddaAndelarISamfalligheter")]
        public bool? OutreddaAndelarISamfalligheter { get; set; }

        [JsonPropertyName("forvarvstillstandOmarrendering")]
        public bool? ForvarvstillstandOmarrendering { get; set; }

        [JsonPropertyName("kronohemman")]
        public bool? Kronohemman { get; set; }

        [JsonPropertyName("delagareOfullstandigtRedovisade")]
        public bool? DelagareOfullstandigtRedovisade { get; set; }

        [JsonPropertyName("felIFR")]
        public bool? FelIfr { get; set; }

        [JsonPropertyName("underAjourforingIFR")]
        public bool? UnderAjourforingIfr { get; set; }

        [JsonPropertyName("senasteAjourforingIFR")]
        public string SenasteAjourforingIfr { get; set; }

        [JsonPropertyName("utanforBevakningskrets")]
        public bool? UtanforBevakningskrets { get; set; }

        [JsonPropertyName("preliminarTypkod")]
        public string PreliminarTypkod { get; set; }

        [JsonPropertyName("har3DOmrade")]
        public bool? Har3DOmrade { get; set; }

        [JsonPropertyName("ar3DUrholkad")]
        public bool? Ar3DUrholkad { get; set; }

        [JsonPropertyName("andelAvserUtforandeOchDrift")]
        public bool? AndelAvserUtforandeOchDrift { get; set; }

        [JsonPropertyName("samfallighetFarAndraAndel")]
        public bool? SamfallighetFarAndraAndel { get; set; }

        [JsonPropertyName("andelAvserEndastDrift")]
        public bool? AndelAvserEndastDrift { get; set; }

        [JsonPropertyName("summaAndelstal")]
        public string SummaAndelstal { get; set; }

        [JsonPropertyName("arAgarlagenhet")]
        public bool? ArAgarlagenhet { get; set; }

        [JsonPropertyName("arUrholkadAvAgarlagenhet")]
        public bool? ArUrholkadAvAgarlagenhet { get; set; }

        [JsonPropertyName("forvarvstillstandGlesbygd")]
        public bool? ForvarvstillstandGlesbygd { get; set; }

        [JsonPropertyName("fnr")]
        public long? Fnr { get; set; }

        [JsonPropertyName("cfdFnr")]
        public string CfdFnr { get; set; }

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }
    }
}
