// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var belagenhetsadress = Belagenhetsadress.FromJson(jsonString);

using Newtonsoft.Json;

namespace FbService.QuickType.FastighetSearchBelagenhetsadress
{
    public class FastighetSearchBelagenhetsadress
    {
        [JsonProperty("statusKod")]
        public long StatusKod { get; set; }

        [JsonProperty("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonProperty("fel")]
        public string[] Fel { get; set; }

        [JsonProperty("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("belagenhetsadress")]
        public string Belagenhetsadress { get; set; }

        [JsonProperty("grupp")]
        public Grupp[] Grupp { get; set; }
    }

    public class Grupp
    {
        [JsonProperty("fnr")]
        public int Fnr { get; set; }

        [JsonProperty("cfdFnr")]
        public string CfdFnr { get; set; }

        [JsonProperty("uuid")]
        public string Uuid { get; set; }
    }
}
