// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var belagenhetsadress = Belagenhetsadress.FromJson(jsonString);

using System.Text.Json.Serialization;

namespace FbService.QuickType.FastighetSearchBelagenhetsadress
{
    public class FastighetSearchBelagenhetsadress
    {
        [JsonPropertyName("statusKod")]
        public long StatusKod { get; set; }

        [JsonPropertyName("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonPropertyName("fel")]
        public string[] Fel { get; set; }

        [JsonPropertyName("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonPropertyName("belagenhetsadress")]
        public string Belagenhetsadress { get; set; }

        [JsonPropertyName("grupp")]
        public Grupp[] Grupp { get; set; }
    }

    public class Grupp
    {
        [JsonPropertyName("fnr")]
        public int Fnr { get; set; }

        [JsonPropertyName("cfdFnr")]
        public string CfdFnr { get; set; }

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }
    }
}
