// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var fastighetSearchFranPunkt = FastighetSearchFranPunkt.FromJson(jsonString);

using System.Text.Json.Serialization;

namespace FbService.QuickType.FastighetSearchFranPunkt
{
    public class FastighetSearchFranPunkt
    {
        [JsonPropertyName("statusKod")]
        public long? StatusKod { get; set; }

        [JsonPropertyName("statusMeddelande")]
        public string StatusMeddelande { get; set; }

        [JsonPropertyName("fel")]
        public string[] Fel { get; set; }

        [JsonPropertyName("data")]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonPropertyName("fnr")]
        public int Fnr { get; set; }

        [JsonPropertyName("cfdFnr")]
        public string CfdFnr { get; set; }

        [JsonPropertyName("uuid")]
        public string Uuid { get; set; }
    }
}
