// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var fastighetSearchFranPunkt = FastighetSearchFranPunkt.FromJson(jsonString);

using Newtonsoft.Json;

namespace FbService.QuickType.FastighetSearchFranPunkt
{
    public class FastighetSearchFranPunkt
    {
        [JsonProperty("statusKod", NullValueHandling = NullValueHandling.Ignore)]
        public long? StatusKod { get; set; }

        [JsonProperty("statusMeddelande", NullValueHandling = NullValueHandling.Ignore)]
        public string StatusMeddelande { get; set; }

        [JsonProperty("fel", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Fel { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public Datum[] Data { get; set; }
    }

    public class Datum
    {
        [JsonProperty("fnr", NullValueHandling = NullValueHandling.Ignore)]
        public string Fnr { get; set; }

        [JsonProperty("cfdFnr", NullValueHandling = NullValueHandling.Ignore)]
        public string CfdFnr { get; set; }

        [JsonProperty("uuid", NullValueHandling = NullValueHandling.Ignore)]
        public string Uuid { get; set; }
    }
}
